import Foundation

extension Journey {
    static let armorOfGraceDays1to6: [JourneyDay] = [
        JourneyDay(
            journeyID: "armor_of_grace",
            dayNumber: 1,
            title: "Be Strong in the Lord",
            scripture: "\"Finally, be strong in the Lord and in his mighty power.\"",
            scriptureReference: "Ephesians 6:10",
            reflection: "There is a particular kind of exhaustion that comes from trying to be the strong one. The one who holds it together for everyone else. The one who shows up, plans ahead, carries the weight, and keeps going — on fumes and sheer willpower. If that sounds familiar, this word from Paul is not a demand. It is an invitation. Be strong in the Lord. Not in your discipline. Not in your schedule. Not in your ability to cope. In Him.\n\nThe Greek word Paul uses here — endunamoō — means to be empowered, to receive strength from an external source. God isn't asking you to dig deeper into reserves you don't have. He's offering you access to His own mighty power — the same power that raised Jesus from the dead, the same power that parts seas and calls stars by name. That power is available to you, right now, in the middle of your ordinary, overwhelming, beautiful life.\n\nThis journey begins not with a battle strategy but with an admission: your strength isn't enough, and it was never meant to be. The first step to putting on the armor of God is releasing the armor you've been forging yourself — the self-sufficiency, the performance, the keeping-it-all-together persona. Let it go. God's strength is not a supplement to yours. It replaces it entirely, and what He gives is so much better.",
            prompt: "Where have you been relying on your own strength instead of God's? Be specific — is it in your relationships, your work, your motherhood, your battle with anxiety or comparison? What would it feel like to stop striving and start receiving His strength in that area?",
            actionStep: "Write Ephesians 6:10 on a card or in your notes app. When you feel the pull to white-knuckle something today, pause, read it aloud, and take a breath. Ask God to exchange your striving for His strength in that moment.",
            prayer: "Lord, I am tired of being strong in my own power. I come to You not with more effort but with open hands. I receive Your mighty power today — not as a reward for doing everything right, but as a gift freely given to Your daughter. Where I am weak, be strong. Where I am weary, be my rest. Where I am afraid, be my courage. I don't need to manufacture strength anymore. I need You. And today, I choose You. Amen."
        ),
        JourneyDay(
            journeyID: "armor_of_grace",
            dayNumber: 2,
            title: "Why We Need Armor",
            scripture: "\"Put on the full armor of God, so that you can take your stand against the devil's schemes. For our struggle is not against flesh and blood, but against the rulers, against the authorities, against the powers of this dark world and against the spiritual forces of evil in the heavenly realms.\"",
            scriptureReference: "Ephesians 6:11-12",
            reflection: "Have you ever felt like your life has an undercurrent of opposition — like something is always working against you, whispering doubt at your most vulnerable moments, stirring conflict when things start going well, amplifying fear in the dead of night? You are not imagining it. There is a real enemy, and he has a real strategy — and Paul calls it a scheme. A scheme is not a random attack. It is a calculated, personalized, targeted plan designed specifically for your weaknesses, your story, your season.\n\nThe enemy knows which lies you are most likely to believe. He knows whether fear or pride is your greater vulnerability. He knows which relationships to strain and which dreams to suffocate. He doesn't fight fairly, and he doesn't fight visibly. That is precisely why Paul says your struggle is not against flesh and blood. When you see that difficult coworker as your enemy, you are fighting the wrong battle. When you blame your husband, your circumstances, your body, your past — you are aiming at shadows while the real archer goes unnoticed.\n\nThis is not cause for fear. It is cause for clarity. Knowing your real enemy means you can fight your real battle. And here is the most important thing: Paul doesn't say the armor is for extraordinary women in exceptional circumstances. He says put on the full armor — every day, all of it — because the battle is constant. You are not paranoid for taking spiritual opposition seriously. You are wise. The woman who understands the battle she is in is the woman who is ready to stand.",
            prompt: "What schemes has the enemy been running against you in this season? Look for patterns — the recurring lies, the persistent fears, the relationships that seem to stay strained. Name them honestly. What does it shift in you to recognize these as spiritual attacks rather than random hardships?",
            actionStep: "Create a simple morning ritual this week: before you check your phone, spend two minutes in prayer. Ask God to reveal any schemes at work in your life and to arm you for what's ahead that day. Even two minutes of intentional preparation changes the posture of your whole morning.",
            prayer: "Father, open my eyes to the battle I am in. I have been fighting the wrong enemies — getting frustrated with people, blaming circumstances, turning my frustration inward. Forgive me for missing the real struggle. I want to fight the real battle. Help me see through the visible to the spiritual reality behind it. And in that awareness, not fear — give me Your courage and Your clarity. I am not fighting alone, and I am not fighting blind. Amen."
        ),
        JourneyDay(
            journeyID: "armor_of_grace",
            dayNumber: 3,
            title: "Standing Firm",
            scripture: "\"Therefore put on the full armor of God, so that when the day of evil comes, you may be able to stand your ground, and after you have done everything, to stand.\"",
            scriptureReference: "Ephesians 6:13",
            reflection: "Notice what Paul does not say. He does not say advance, conquer, or destroy. He says stand. Three times in these verses, the call is simply to stand your ground. There is something quietly radical about that. In a culture that celebrates momentum, achievement, and forward motion, standing — staying rooted when everything in you wants to run, collapse, or give in — is one of the most powerful things a woman of faith can do.\n\nThe phrase \"when the day of evil comes\" is significant. Not if — when. Paul is not speaking to women in theory. He is speaking to you in the reality of your actual life. There will be days when the pressure is immense, when the grief is deep, when the lies are loud, when the ground feels unsteady beneath your feet. Those days are coming, and the armor is for those days. The question isn't whether the storm will come. The question is whether you will still be standing when it passes.\n\nAnd then there is this tender phrase at the end: after you have done everything, to stand. There is grace here for the woman who has prayed, sought counsel, done the work, and still feels like she's barely holding on. Sometimes doing everything means simply refusing to quit. Sometimes the most faithful thing you can do in your hardest season is stay. Stay in your faith. Stay in the Word. Stay in community. Stay trusting God even when you cannot see what He is doing. That is not passivity. That is armor. That is strength.",
            prompt: "Where in your life do you most need to simply stand your ground right now? In a conviction, a boundary, your identity, a relationship, your faith in a dry season? What does standing firm look like practically in that specific place — not advancing, not retreating, just holding the ground God has given you?",
            actionStep: "Identify one area where you have been slowly retreating — from a truth you believe, a boundary you set, a conviction you hold, or a practice that grounds your faith. Take one concrete step back toward standing firm today. It doesn't have to be dramatic. It just has to be honest.",
            prayer: "Father, give me the quiet, fierce courage to stand. Not to advance in my own ambition, not to run in my own fear — just to stand. Where I have been retreating, call me back. Where I have been wavering, anchor me. On the days when evil presses in and everything shakes, let me be found still standing — not because I was strong enough, but because You held me. I trust You with my footing. Amen."
        ),
        JourneyDay(
            journeyID: "armor_of_grace",
            dayNumber: 4,
            title: "The Belt of Truth — Part 1",
            scripture: "\"Stand firm then, with the belt of truth buckled around your waist... and you will know the truth, and the truth will set you free.\"",
            scriptureReference: "Ephesians 6:14a; John 8:32",
            reflection: "In a Roman soldier's armor, the belt was foundational. It was not the most dramatic piece — no one wrote songs about the belt — but without it, everything else failed. The sword had nowhere to hang. The breastplate shifted. The tunic tangled the soldier's feet in the heat of battle. The belt held the entire system together. Paul knew exactly what he was doing when he listed it first. Truth is what holds your whole spiritual life in order.\n\nWhen you believe lies — about who God is, about who you are, about what you deserve or don't deserve — everything else in your life begins to come undone in subtle ways. Your relationships fray. Your decisions drift. Your sense of purpose blurs. You don't always notice the lies because they rarely announce themselves as lies. They come dressed as reasonable fears, familiar insecurities, and voices that sound so much like your own. \"You're too much.\" \"You're not enough.\" \"God must be disappointed in you.\" \"Nothing is ever going to change.\" Lies. Every one of them. And they are tangling your feet.\n\nJesus says the truth will set you free — not comfort you, not encourage you, but actually, actively liberate you. That is a promise with weight. The belt of truth is not about winning theological debates. It is about the freedom that comes when you know — really know — what is actually true about God and about yourself. That freedom changes how you walk, how you love, how you fight, and how you stand.",
            prompt: "What is one lie you have been living under — perhaps for years — about your worth, your identity, your capacity, or your relationship with God? Where did it come from? And what is the specific truth from Scripture that God wants to replace it with? Take time with this. Don't rush past the lie — naming it precisely is the first step to being free from it.",
            actionStep: "Write the lie on one side of a card and the corresponding truth from Scripture on the other. Carry it with you today. Each time the lie surfaces — in a thought, a conversation, a moment of self-doubt — flip the card and read the truth aloud. Your voice speaking truth is a weapon.",
            prayer: "God of all truth, I ask You to reveal the lies I am living under — especially the ones I've stopped questioning because they've been with me so long. I want to be free. Not just intellectually corrected, but genuinely, deeply free in the way that only truth can accomplish. Buckle me with Your Word today. Where the enemy has tangled my footing with deception, cut through it with what is real and true and eternal. I choose truth today, even when it is uncomfortable. Set me free. Amen."
        ),
        JourneyDay(
            journeyID: "armor_of_grace",
            dayNumber: 5,
            title: "The Belt of Truth — Part 2",
            scripture: "\"Stand firm then, with the belt of truth buckled around your waist... Sanctify them by the truth; your word is truth.\"",
            scriptureReference: "Ephesians 6:14a; John 17:17",
            reflection: "In John 17, Jesus is praying for you. Not just for His disciples gathered around Him that night, but for every woman who would ever follow Him — including you, right now, today. And one of the things He asks for you is this: sanctify them by the truth. The word sanctify means to set apart, to make holy, to transform. Jesus is asking the Father to use truth as the tool of your transformation. Not your efforts. Not your performance. Truth.\n\nThis is what makes the belt so personal. Truth is not just a philosophical category or a doctrinal checklist. It is the living Word of God, actively working in you — setting you apart, reshaping your thinking, healing what is broken, exposing what needs to change. When you spend time in Scripture, you are not just gathering information. You are submitting yourself to the transforming work of truth. You are letting God's Word do what Jesus prayed it would do — make you holy, set you apart, shape you into the woman He created you to be.\n\nHere is the invitation: buckle truth around you not as a rule to follow but as a relationship to inhabit. Know the Word not to win arguments but to stay close to the One who is Truth Himself. Jesus didn't just speak truth — He said I am the way, the truth, and the life. The belt of truth is, at its deepest level, a nearness to Jesus. And the closer you are to Him, the more the lies simply lose their grip.",
            prompt: "How is your relationship with God's Word right now — honest answer? Is it a living, transforming presence in your daily life, or has it become routine, distant, or neglected? What is one specific way you could let the truth of Scripture do the sanctifying work Jesus prayed for in your actual life this week?",
            actionStep: "Choose one passage of Scripture — even just two or three verses — that speaks directly to something God is working on in you right now. Read it slowly, out loud, three times today. Not to study it, but to let it settle. Ask God to use His Word to do exactly what Jesus prayed: to sanctify and transform you through truth.",
            prayer: "Jesus, You prayed for me — You prayed that truth would sanctify me, set me apart, make me holy. I want that. I want to be transformed by Your Word, not just informed by it. Today I come to the truth not as a duty but as a daughter coming home. Speak to me through Your Word. Reshape what is crooked in me. Heal what is broken. Set apart what You have claimed. I submit to the transforming power of Your truth. Amen."
        ),
        JourneyDay(
            journeyID: "armor_of_grace",
            dayNumber: 6,
            title: "Living in Truth Daily",
            scripture: "\"Yet you desired faithfulness even in the womb; you taught me wisdom in that secret place... The Lord detests lying lips, but he delights in people who are trustworthy.\"",
            scriptureReference: "Psalm 51:6; Proverbs 12:22",
            reflection: "It is one thing to believe the right things about truth. It is another to live truthfully — in the private places, in the small moments, in the conversations where honesty costs something. David, writing Psalm 51 in the raw aftermath of his greatest failure, touches on something profound: God desires truth in the inmost parts. Not performance. Not the polished, presentable version of you. Truth in the places no one else sees. That is where the belt is really buckled or really left hanging.\n\nLiving in truth daily looks like more than avoiding outright lies. It looks like honesty with yourself — acknowledging your struggles, owning your patterns, bringing your real self to God instead of the self you think He'd prefer. It looks like authenticity with others — resisting the pressure to perform, to say \"I'm fine\" when you aren't, to project a version of your life that isn't actually yours. It looks like integrity — being the same woman in private that you are in public, making decisions in the dark that align with what you profess in the light.\n\nProverbs says God delights in people who are trustworthy. That word in Hebrew — emunah — is the same root as the word for faith. Trustworthiness and faithfulness are woven together. A woman of truth is a woman whose inner life and outer life match, whose word can be trusted, whose faith in a God of truth produces a life that reflects it. This is not about perfection. It is about direction — consistently orienting yourself toward what is real and true, in the hidden places first.",
            prompt: "Where are you living with a gap between the version of yourself you present to others and who you actually are before God? Is there an area of your inner life — a struggle, a habit, a doubt — that you have been hiding rather than bringing into the light? What would it look like to live more truthfully in that specific space today?",
            actionStep: "Spend five minutes in honest, unfiltered prayer — no performance, no tidy language. Tell God exactly what is true about where you are right now: the fear, the doubt, the longing, the thing you've been afraid to say out loud. Then read Psalm 51:6 again. His desire is for truth in your inmost parts — which means He can handle whatever is actually in there.",
            prayer: "Lord, You see the inmost parts of me — the places I try to polish before I bring them to You, the struggles I'd rather manage quietly than surrender honestly. I want to be a woman of truth from the inside out. Help me close the gap between who I appear to be and who I actually am. Teach me the wisdom that comes from honest, humble, unguarded communion with You. Where I have used half-truths to protect myself, give me the courage of full honesty. I want to be trustworthy — to You, to myself, to the people in my life. Make me that woman. Amen."
        )
    ]
}
