import Foundation

// MARK: - Journey Content: Premium Journey Sample Days
/// Sample days for remaining premium journeys (5 days each for MVP)

extension JourneyDay {
    // MARK: - Becoming a Prayer Warrior
    static let prayerWarriorDays: [JourneyDay] = [
        JourneyDay(journeyID: "prayer_warrior", dayNumber: 1, title: "Prayer Changes Everything", scripture: "The prayer of a righteous person is powerful and effective.", scriptureReference: "James 5:16", reflection: "Prayer isn't a last resort — it's your first response, your most powerful weapon, and your deepest intimacy with God. This journey will transform your prayer life from routine to revolutionary.", prompt: "How would you describe your prayer life right now? Vibrant or routine? Honest or formal?", actionStep: "Set aside 10 minutes of uninterrupted prayer today. No agenda — just talk to God.", prayer: "Father, revolutionize my prayer life. Take it from routine to relationship. I want to know the power of prayer — not in theory, but in practice. Amen."),
        JourneyDay(journeyID: "prayer_warrior", dayNumber: 2, title: "Praying with Boldness", scripture: "Let us then approach God's throne of grace with confidence, so that we may receive mercy and find grace to help us in our time of need.", scriptureReference: "Hebrews 4:16", reflection: "God invites bold prayers. Not timid, carefully worded, safe prayers — but audacious, faith-filled, kingdom-shaking prayers.", prompt: "What bold prayer have you been afraid to pray? Why are you holding back?", actionStep: "Pray your boldest prayer today. The one that feels too big, too audacious, too impossible.", prayer: "Lord, I approach Your throne with confidence — not in myself, but in Your invitation. I bring my boldest prayer before You today. Amen."),
        JourneyDay(journeyID: "prayer_warrior", dayNumber: 3, title: "Praying Scripture", scripture: "Your word is a lamp for my feet, a light on my path.", scriptureReference: "Psalm 119:105", reflection: "When you pray God's Word back to Him, you align your prayers with His will. Scripture-soaked prayers are faith-filled and powerful.", prompt: "Do you pray Scripture? What verse could you turn into a prayer today?", actionStep: "Choose one verse and pray it over yourself, your family, or a situation throughout the day.", prayer: "Lord, Your Word is my prayer language. Help me pray Scripture over every area of my life. Amen."),
        JourneyDay(journeyID: "prayer_warrior", dayNumber: 4, title: "Intercession: Fighting for Others", scripture: "I urge, then, first of all, that petitions, prayers, intercession and thanksgiving be made for all people.", scriptureReference: "1 Timothy 2:1", reflection: "Intercession is one of the most selfless acts of love. When you pray for others, you participate in God's work in their lives.", prompt: "Who needs your prayers today? A friend, a family member, a stranger, a leader?", actionStep: "Write down five names and pray specifically for each person today.", prayer: "Father, I stand in the gap for those You've placed on my heart. Move powerfully in their lives. Amen."),
        JourneyDay(journeyID: "prayer_warrior", dayNumber: 5, title: "When Prayer Feels Hard", scripture: "In the same way, the Spirit helps us in our weakness. We do not know what we ought to pray for, but the Spirit himself intercedes for us.", scriptureReference: "Romans 8:26", reflection: "Sometimes prayer feels empty, dry, or impossible. That's when the Spirit takes over. You don't have to have the right words — just show up.", prompt: "When prayer feels hard, what do you do? How does knowing the Spirit intercedes for you change things?", actionStep: "If prayer feels difficult today, simply sit in God's presence. Let the Spirit pray through you.", prayer: "Holy Spirit, pray through me when I don't have the words. I show up — imperfect, weary, wordless — and trust You to intercede. Amen."),
    ]

    // MARK: - Gentle Strength
    static let gentleStrengthDays: [JourneyDay] = [
        JourneyDay(journeyID: "gentle_strength", dayNumber: 1, title: "Meekness Is Not Weakness", scripture: "But the meek will inherit the earth and enjoy peace and prosperity.", scriptureReference: "Psalm 37:11", reflection: "The world says meekness is weakness. God says it inherits the earth. Meekness is strength under control — power surrendered to God's purposes.", prompt: "How do you define meekness? Has the world's definition distorted your understanding?", actionStep: "Practice one act of meekness today — responding gently when you want to react harshly.", prayer: "Lord, redefine strength for me. Help me see meekness as You see it — power under Your control. Amen."),
        JourneyDay(journeyID: "gentle_strength", dayNumber: 2, title: "The Unfading Beauty of a Gentle Spirit", scripture: "Your beauty should be that of your inner self, the unfading beauty of a gentle and quiet spirit, which is of great worth in God's sight.", scriptureReference: "1 Peter 3:4", reflection: "A gentle and quiet spirit isn't about being silent or passive. It's about inner peace so deep that external chaos can't shake it. That's unfading beauty.", prompt: "What does a 'gentle and quiet spirit' look like in your daily life — not silence, but unshakeable peace?", actionStep: "In a chaotic moment today, practice inner stillness. Let peace rule before words do.", prayer: "Father, cultivate in me the unfading beauty of a gentle spirit — rooted in peace, not passivity. Amen."),
        JourneyDay(journeyID: "gentle_strength", dayNumber: 3, title: "Gentle Answer", scripture: "A gentle answer turns away wrath, but a harsh word stirs up anger.", scriptureReference: "Proverbs 15:1", reflection: "Your words have the power to escalate or de-escalate any situation. A gentle answer is a choice — a powerful, courageous choice.", prompt: "Think of a recent conflict. How could a gentle answer have changed the outcome?", actionStep: "The next time tension rises today, pause 5 seconds before responding. Choose gentleness.", prayer: "Lord, put gentle words on my tongue today. When I want to react, help me respond with grace. Amen."),
        JourneyDay(journeyID: "gentle_strength", dayNumber: 4, title: "Fruit of Self-Control", scripture: "But the fruit of the Spirit is... self-control.", scriptureReference: "Galatians 5:22-23", reflection: "Self-control is the Spirit's fruit, not your willpower. It's not about trying harder — it's about surrendering more.", prompt: "Where do you need more Spirit-led self-control? In words, habits, reactions, or thoughts?", actionStep: "Identify one area needing self-control and surrender it to the Spirit's work today.", prayer: "Spirit, produce Your fruit of self-control in me — not through my striving, but through Your power. Amen."),
        JourneyDay(journeyID: "gentle_strength", dayNumber: 5, title: "Power Made Perfect in Weakness", scripture: "My grace is sufficient for you, for my power is made perfect in weakness.", scriptureReference: "2 Corinthians 12:9", reflection: "True strength isn't hiding your weakness — it's letting God's power show up in it. Your vulnerability is the stage for His glory.", prompt: "What weakness are you trying to hide? What if you let God's power be displayed there instead?", actionStep: "Share a vulnerability with a trusted friend today. Let God's strength show up in your honesty.", prayer: "Lord, I stop hiding my weakness and invite Your power in. Be glorified in my vulnerability. Amen."),
    ]

    // MARK: - Freedom from Comparison
    static let freedomComparisonDays: [JourneyDay] = [
        JourneyDay(journeyID: "freedom_from_comparison", dayNumber: 1, title: "The Comparison Trap", scripture: "Each one should test their own actions. Then they can take pride in themselves alone, without comparing themselves to someone else.", scriptureReference: "Galatians 6:4", reflection: "Comparison is the thief of joy, the killer of contentment, and the enemy of your unique calling. Today, we name the trap and begin to walk free.", prompt: "Who do you most compare yourself to? What specifically triggers that comparison?", actionStep: "Unfollow or mute one social media account that consistently triggers comparison.", prayer: "Lord, free me from the comparison trap. Help me run my own race with joy and gratitude. Amen."),
        JourneyDay(journeyID: "freedom_from_comparison", dayNumber: 2, title: "Fearfully and Wonderfully Made", scripture: "I praise you because I am fearfully and wonderfully made.", scriptureReference: "Psalm 139:14", reflection: "God didn't accidentally make you. Every detail was intentional. Comparing His masterpiece to another diminishes the Artist.", prompt: "What about yourself do you struggle to accept? Can you see it as God's intentional design?", actionStep: "Look in the mirror today and speak Psalm 139:14 over yourself — with conviction.", prayer: "Creator God, I am fearfully and wonderfully made. Help me see myself through Your eyes, not the world's. Amen."),
        JourneyDay(journeyID: "freedom_from_comparison", dayNumber: 3, title: "Celebrating Others Without Diminishing Yourself", scripture: "Rejoice with those who rejoice.", scriptureReference: "Romans 12:15", reflection: "You can celebrate someone else's win without it being your loss. When envy whispers, let gratitude answer.", prompt: "Can you genuinely celebrate someone else's success today — without feeling diminished?", actionStep: "Send a sincere congratulation or encouragement to someone who's experiencing a win right now.", prayer: "Lord, give me a heart that genuinely celebrates others. Let their blessings inspire, not diminish me. Amen."),
        JourneyDay(journeyID: "freedom_from_comparison", dayNumber: 4, title: "Your Unique Calling", scripture: "For we are God's handiwork, created in Christ Jesus to do good works, which God prepared in advance for us to do.", scriptureReference: "Ephesians 2:10", reflection: "God prepared specific works for you — not for her. Your calling is unique, irreplaceable, and needed.", prompt: "What unique gifts, experiences, and perspectives has God given you that no one else has?", actionStep: "Write down three things that make your calling uniquely yours. Celebrate them.", prayer: "Father, I embrace my unique calling. Help me stop coveting someone else's path and fully walk mine. Amen."),
        JourneyDay(journeyID: "freedom_from_comparison", dayNumber: 5, title: "Running Your Own Race", scripture: "Let us run with perseverance the race marked out for us.", scriptureReference: "Hebrews 12:1", reflection: "Your race is marked out for you — not for her. Looking sideways at another runner only slows you down.", prompt: "What happens when you take your eyes off your own lane? How can you refocus on the race God has for you?", actionStep: "Write a personal race declaration: 'I run MY race — with perseverance, joy, and my eyes on Jesus.'", prayer: "Jesus, I fix my eyes on You — the author and finisher of MY faith. I run my race. No one else's. Amen."),
    ]

    // MARK: - Cultivating Peace
    static let cultivatingPeaceDays: [JourneyDay] = [
        JourneyDay(journeyID: "cultivating_peace", dayNumber: 1, title: "The Peace Jesus Gives", scripture: "Peace I leave with you; my peace I give you. I do not give to you as the world gives. Do not let your hearts be troubled and do not be afraid.", scriptureReference: "John 14:27", reflection: "The world offers temporary peace — when circumstances align. Jesus offers permanent peace — regardless of circumstances. His peace is a gift, not an achievement.", prompt: "What counterfeit 'peace' have you been chasing? Control? Approval? Perfection? A perfect schedule?", actionStep: "When anxiety surfaces today, pause and say: 'I receive the peace of Jesus — not the world's version.'", prayer: "Jesus, I receive Your peace today — the real, unshakeable, circumstances-independent kind. Calm my heart. Amen."),
        JourneyDay(journeyID: "cultivating_peace", dayNumber: 2, title: "Peace That Guards", scripture: "And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus.", scriptureReference: "Philippians 4:7", reflection: "God's peace is a guard — a sentinel posted at the door of your heart and mind. It transcends understanding because it doesn't require good circumstances to exist.", prompt: "Where do you need God's peace to stand guard today — over your heart, your mind, your home?", actionStep: "Write Philippians 4:7 on a card and place it at the entrance of your home as a reminder.", prayer: "Father, post Your peace as a guard over my heart and mind today. I don't need to understand — I just need Your peace. Amen."),
        JourneyDay(journeyID: "cultivating_peace", dayNumber: 3, title: "Peacemaker, Not Peacekeeper", scripture: "Blessed are the peacemakers, for they will be called children of God.", scriptureReference: "Matthew 5:9", reflection: "Peacekeeping avoids conflict at any cost. Peacemaking pursues wholeness through truth and love. God calls you to make peace, not just keep it.", prompt: "Are you a peacekeeper (avoiding) or a peacemaker (pursuing)? What's the difference in your life?", actionStep: "Address one avoided conversation today with truth and love. Make peace, don't just keep it.", prayer: "Lord, make me a peacemaker — not someone who avoids, but someone who pursues wholeness with courage and grace. Amen."),
        JourneyDay(journeyID: "cultivating_peace", dayNumber: 4, title: "Creating Peaceful Spaces", scripture: "If it is possible, as far as it depends on you, live at peace with everyone.", scriptureReference: "Romans 12:18", reflection: "You may not be able to control others, but you can control the atmosphere you carry. Your home, your conversations, your presence — can be spaces of peace.", prompt: "What environment in your life needs more peace? What can you do — 'as far as it depends on you' — to cultivate it?", actionStep: "Transform one space today into a more peaceful environment — declutter, light a candle, play worship music, speak gently.", prayer: "Lord, help me cultivate peace in every space I enter — my home, my workplace, my relationships. Let peace follow me. Amen."),
        JourneyDay(journeyID: "cultivating_peace", dayNumber: 5, title: "Resting in His Sovereignty", scripture: "Be still, and know that I am God.", scriptureReference: "Psalm 46:10", reflection: "The deepest peace comes from knowing that God is sovereign — He is in control, even when you are not. Stillness isn't inactivity; it's trust.", prompt: "What are you restless about? Can you be still and trust God's sovereignty over it?", actionStep: "Practice 5 minutes of complete stillness today — no phone, no noise, no agenda. Just rest in His sovereignty.", prayer: "God, I am still. You are God. I rest in Your sovereignty today. I don't need to understand everything — I just need to trust You. Amen."),
    ]
}
