import Foundation

extension Journey {
    static let rootedIdentityDays1to6: [JourneyDay] = [
        JourneyDay(
            journeyID: "rooted_identity",
            dayNumber: 1,
            title: "Chosen Before the World Began",
            scripture: "\"For he chose us in him before the creation of the world to be holy and blameless in his sight.\"",
            scriptureReference: "Ephesians 1:4",
            reflection: "Before the first word was spoken into existence, before light split from darkness, before a single star was hung in the sky — God chose you. Let that land for a moment. His choice wasn't made after reviewing your résumé or waiting to see how you'd turn out. It was settled in eternity past, in the quiet counsel of a God who already knew every beautiful and broken thing about you and said yes anyway. This is where your identity begins — not in what you've done, not in what others think of you, but in the sovereign, unhurried love of a Father who picked you before time itself began.\n\nSo many of us build our sense of worth on foundations that shift — performance, appearance, relationships, achievements. And when those things waver, we waver with them. But the truth of Ephesians 1:4 is an unshakeable anchor. You were chosen in Him, which means your standing isn't based on your own merit but on Christ's. You are seen through the lens of His belovedness. That's not something you can earn or lose. It simply is — as certain as creation itself.\n\nToday, let this truth do its slow, deep work in you. You don't have to prove yourself to a God who already chose you. You don't have to perform for an audience whose approval you already have. The most powerful thing you can do is simply receive it — the choosing, the love, the identity that was yours before you drew your first breath.",
            prompt: "Where do you most often seek your sense of worth — from performance, relationships, appearance, or something else? How does the truth that God chose you before the world began challenge or reframe that foundation?",
            actionStep: "Write \"I am chosen\" somewhere you will see it repeatedly today — a sticky note on your mirror, a reminder on your phone, the back of your hand. Each time you notice it, resist the urge to qualify it or brush past it. Pause, breathe, and receive it as truth.",
            prayer: "Father, it is almost too much to take in — that You chose me before the world began. Not after I proved myself, not once I had it together, but before time itself. I confess that I have been looking for my worth in all the wrong places, and I'm tired. Today I anchor my identity here, in Your choosing. When the voices of doubt and comparison grow loud, let this truth be louder still. I am Yours — chosen, holy, and blameless in Your sight through Christ. That is more than enough. Amen."
        ),
        JourneyDay(
            journeyID: "rooted_identity",
            dayNumber: 2,
            title: "Adopted as His Daughter",
            scripture: "\"He predestined us for adoption to sonship through Jesus Christ, in accordance with his pleasure and will.\"",
            scriptureReference: "Ephesians 1:5",
            reflection: "Adoption is never an accident. It is one of the most intentional acts a person can take — choosing, pursuing, and legally claiming a child as your own. There is paperwork and waiting and cost, and it is all done for one reason: love. When Paul tells us that God predestined us for adoption, he is using this language deliberately. You were not added to God's family out of obligation or coincidence. You were pursued. You were claimed. You were brought in through a process that cost everything — the life of His own Son — and it was done, Paul says, in accordance with His pleasure and will. God delighted in doing this for you.\n\nMaybe you grew up in a home where belonging felt fragile or conditional. Maybe you have known what it is to feel like an outsider, like you were always one misstep away from losing your place. Or maybe you've built walls around your heart because it simply hurts too much to need someone and not be sure they'll stay. Whatever your story, hear this: God's adoption of you is permanent. It is legal and sealed. His pleasure in claiming you was not a fleeting emotion — it was an eternal decision ratified in the blood of Jesus and secured by the Holy Spirit within you.\n\nYou are not a spiritual orphan trying to earn your keep in the household of faith. You are a daughter with full rights, full access, and a Father who will never revoke your belonging. You don't have to perform to stay in His good graces. You don't have to shrink or over-function or make yourself useful to deserve a seat at His table. You already have one. He gave it to you — with joy.",
            prompt: "In what areas of your life do you still behave like an orphan — striving for approval, afraid of rejection, or bracing for abandonment — rather than resting in the security of a beloved daughter? What would it look like to live from that place of settled belonging today?",
            actionStep: "Find a quiet moment today and pray the word \"Abba\" — the intimate Aramaic word for father that Jesus Himself used. Sit with the weight of that word. You are not speaking to a distant deity but to a Father who adopted you with pleasure. Let that reality be more than intellectual — let it settle into your body, your posture, your breathing.",
            prayer: "Abba, Father — I want to really mean those words, not just say them. Thank You for adopting me, not out of duty, but out of delight. You wanted me in Your family. You pursued me. You paid for me. On the days when I feel unwanted or unsure of my place, remind me that my belonging is not up for debate. I have a permanent home in You. Help me to stop striving and simply live as Your daughter — loved, settled, and free. Amen."
        ),
        JourneyDay(
            journeyID: "rooted_identity",
            dayNumber: 3,
            title: "Redeemed and Forgiven",
            scripture: "\"In him we have redemption through his blood, the forgiveness of sins, in accordance with the riches of God's grace.\"",
            scriptureReference: "Ephesians 1:7",
            reflection: "Redemption is a marketplace word. In the ancient world, it meant buying someone back — purchasing their freedom at a price. When Paul says \"in him we have redemption through his blood,\" he is describing a transaction: you were held captive, and Jesus paid the ransom. Not with silver or gold, but with His life. And the currency of that exchange is described in staggering terms — not the spare change of God's grace, but the riches of it. He didn't give sparingly. He lavished.\n\nFor many women, the hardest part of this truth isn't believing that God can forgive — it's believing that He already has. We tend to carry our shame like a second skin, rehearsing our failures, bracing for the moment someone finally sees how broken we are underneath. We've intellectually accepted forgiveness but keep returning to the scene of our worst moments as if we owe a debt we can never quite pay off. But that is not what Scripture says. It says we have redemption — present tense, active and complete. There is nothing left to pay. The ransom has been settled in full.\n\nYour past does not define you; it has been purchased. The version of you that made the choices you most regret has been bought back and made new. You are not the sum of your worst days. You are the recipient of the richest grace in all the universe — the kind that reaches into the most shameful corner of your story and says, \"Even this. Especially this. I've got this covered.\"",
            prompt: "Is there something specific — a decision, a season, a version of yourself — where you struggle to fully receive God's forgiveness? What would it mean to stop carrying that shame and trust that the price has already been paid?",
            actionStep: "Write down one thing you've been carrying shame about. Be honest — this is between you and God. Then draw a cross over the words. Speak aloud: \"This is covered. In Christ, I am redeemed. The debt is paid.\" Don't rush past the moment. Stay with it until the words move from your mouth to your heart.",
            prayer: "Jesus, the cost of my redemption was everything — and You paid it anyway. I am humbled and undone by that. Today I want to stop rehearsing what You have already forgiven. I release the shame I've been carrying as if it were mine to manage. It is not. You bore it. You covered it. You paid for it with the riches of Your grace. Help me live in the freedom that cost You everything. I am redeemed. That is true — and I choose today to believe it. Amen."
        ),
        JourneyDay(
            journeyID: "rooted_identity",
            dayNumber: 4,
            title: "Sealed with the Holy Spirit",
            scripture: "\"When you believed, you were marked in him with a seal, the promised Holy Spirit, who is a deposit guaranteeing our inheritance until the redemption of those who are God's possession.\"",
            scriptureReference: "Ephesians 1:13-14",
            reflection: "In the ancient world, a seal carried enormous significance. It was the mark of an owner — pressed into wax on a letter or a contract, it meant that what was sealed was protected, authenticated, and belonged to someone of authority. When Paul says that believers are \"marked with a seal\" — the promised Holy Spirit — he is using this image to tell you something profound about your security. You have been marked. You belong to God. And the Holy Spirit Himself is the evidence of that claim on your life.\n\nBut Paul goes even further. He calls the Spirit a \"deposit\" — the first installment of an inheritance that is coming in full. Think of it like an earnest payment on a house: it's real money, it's a genuine transaction, and it guarantees that the rest is coming. The Holy Spirit living in you right now is God's down payment on eternity. He is not a symbol or a sentiment. He is a Person — active, present, and personal — who dwells within you as the living proof that you are His and that He is coming back for what is His.\n\nWhen your faith feels shaky and your circumstances feel chaotic, the seal holds. When you doubt whether God is really there, the Spirit within you is the answer to that doubt — not a feeling to chase but a presence to return to. You are not on your own. You are not winging it through life hoping God notices. You are marked, claimed, sealed, and guaranteed. He is with you, He is in you, and He is not leaving.",
            prompt: "Do you tend to live as though the Holy Spirit is an occasional visitor or a constant resident? What would change about your daily decisions, your fears, or your sense of identity if you genuinely lived aware of His presence within you?",
            actionStep: "Before each significant moment today — a hard conversation, a decision, a task that makes you anxious — pause and whisper, \"Holy Spirit, You are here. Guide me.\" Don't wait until you feel His presence; practice the awareness as an act of faith. Let this discipline begin to reshape how you move through your day.",
            prayer: "Holy Spirit, I confess that I often live as though I'm alone — as though I have to figure everything out on my own strength, with my own wisdom. But You are not far away. You are within me, sealed there by the Father Himself as a guarantee of everything He has promised. Make me aware of Your presence today — not just intellectually, but in the quietest moments, in the hardest moments, in the most ordinary moments. I am sealed. I am marked as His. And that changes everything. Amen."
        ),
        JourneyDay(
            journeyID: "rooted_identity",
            dayNumber: 5,
            title: "Lavished with Grace",
            scripture: "\"In him we have redemption through his blood, the forgiveness of sins, in accordance with the riches of his grace that he lavished on us.\"",
            scriptureReference: "Ephesians 1:7-8",
            reflection: "Paul could have said that God gave us grace. He could have said God shared it, or dispensed it, or offered it in measure. But instead he uses a word that feels almost extravagant: lavished. To lavish is to give in abundance, to pour out generously, to overflow. It is the opposite of careful rationing. God does not hand out grace in small, controlled doses as if He might run out. He lavishes it — pours it over you like oil at a feast, like rain on dry ground, like the father running toward his prodigal child with a robe and a ring and a celebration that the neighbors couldn't quite understand.\n\nWe live in a world of scarcity thinking, and we often bring that mindset to God. We approach Him as if grace is limited — as if we've used up our portion with our failures, as if His patience for us has a ceiling, as if we need to manage our neediness carefully so we don't wear out our welcome. But grace doesn't work that way. The riches of His grace are not diminished by your drawing on them. They are not depleted by your returning to Him again and again with the same struggles. Every time you come, He lavishes. Every time you fail and return, He lavishes again. That is not weakness on His part — it is the nature of a love that is inherently abundant.\n\nYou don't have to earn grace in small installments. You don't have to prove you deserve the next portion before receiving it. His grace toward you is not measured or managed or metered out. It is lavish — overflowing, generous, almost shockingly abundant. Let yourself be a woman who knows how to receive it.",
            prompt: "In what area of your life are you most prone to scarcity thinking about God's grace — believing you've used too much, that you're too much trouble, or that His patience for you is running thin? How does the word \"lavished\" challenge that belief?",
            actionStep: "Today, when you catch yourself minimizing your need or pre-emptively apologizing in your prayers — \"I know I've asked about this before\" or \"I know I keep failing at this\" — stop. Replace those qualifying phrases with a simple, open-handed request. Practice receiving grace without adding fine print. Let your prayers today be unguarded.",
            prayer: "Father, You lavish grace on me — and I am still learning how to receive that without qualifying it or shrinking from it. Forgive me for treating Your grace as something to ration rather than something to live inside of. Today I want to come to You wide open, without managing my neediness, without pre-apologizing, without carefully limiting how much I ask. You are a God who lavishes. Teach me to be a woman who receives. Pour out Your riches over every dry and ashamed place in me today. Amen."
        ),
        JourneyDay(
            journeyID: "rooted_identity",
            dayNumber: 6,
            title: "Created for Good Works",
            scripture: "\"For we are God's handiwork, created in Christ Jesus to do good works, which God prepared in advance for us to do.\"",
            scriptureReference: "Ephesians 2:10",
            reflection: "The Greek word Paul uses for \"handiwork\" is poiema — the root of our English word poem. You are not a mistake or a rough draft. You are God's poem, His crafted work of art, His masterpiece. That word carries intention and delight — a poet doesn't produce something accidentally, they compose it with care, with each word chosen. In the same way, every part of you was shaped on purpose: your personality, your experiences, your particular gifts, the very way your mind works. None of it is random. It is the deliberate composition of a Creator who was making something beautiful.\n\nAnd a poem has a purpose beyond the page it's written on — it is meant to be read, to move people, to carry meaning out into the world. You were created in Christ Jesus to do good works. Not to earn your identity, but to express it. Not to justify your existence, but to pour it out. Those works were prepared in advance, which means they are not a vague, anxious pressure to do more and be more. They are a specific invitation — a set of moments, relationships, and opportunities God has already arranged for you to step into. The question is not whether you are equipped. The question is whether you are willing to show up.\n\nYou were not made to compare your poem to someone else's or to wait until yours looks more polished before letting it be read. You were made to bloom where you are planted — to do the good works in front of you today, in the ordinary fabric of your actual life, with the gifts that are actually yours. That is enough. That is precisely what you were made for.",
            prompt: "If you truly believed you were God's masterpiece — carefully composed with intention and delight — what would you stop apologizing for about yourself? What good works might you stop hesitating to step into?",
            actionStep: "Refuse to speak negatively about yourself today — your body, your abilities, your capacity, your worth. Each time you catch a critical thought or word forming, pause and replace it with: \"I am God's handiwork.\" At the end of the day, write down one good work — however small — that you showed up for. Receive it as the poem you were made to be.",
            prayer: "Creator God, I am Your poem — and some days I struggle to believe that anything beautiful could be written from my story. But today I choose to trust the Poet over my own assessment. You made me with intention. You prepared works for me before I was born. Help me stop waiting until I feel worthy enough to step into what You've already prepared. Forgive me for the times I've called Your craftsmanship anything less than good. I am Your masterpiece — and I will live like it today. Amen."
        ),
    ]
}
